return {
	{
		lenguaje = "C / C++ / CUDA",
		id = "clangd",
		enable = true,
		filetypes = { "c", "cpp", "cuda" },
		root_files = { "compile_commands.json", "compile_flags.txt", ".git", ".jj" },
	},
	--{
	--	lenguaje = "Rust",
	--	id = "rust_analyzer",
	--	enable = false,
	--	filetypes = { "rust" },
	--	root_files = { "Cargo.toml", ".git", ".jj" },
	--},
	{
		lenguaje = "Go",
		id = "gopls",
		enable = true,
		filetypes = { "go", "gomod", "gowork", "gotmpl" },
		root_files = { "go.work", "go.mod", ".git", ".jj" },
	},
	{
		lenguaje = "Lua",
		id = "lua_ls",
		enable = true,
		filetypes = { "lua" },
		root_files = { "init.lua", ".git", ".jj" },
	},
	{
		lenguaje = "Python",
		id = "pylsp",
		enable = true,
		filetypes = { "python" },
		root_files = { "pyproject.toml", "setup.py", "requirements.txt", ".git", ".jj" },
	},
	{
		lenguaje = "HTML",
		id = "html",
		enable = true,
		filetypes = { "html" },
		root_files = { "package.json", ".git", ".jj" },
	},
	{
		lenguaje = "Web (JS / TS / React)",
		id = "vtsls",
		enable = true,
		filetypes = { "javascript", "typescript", "javascriptreact", "typescriptreact" },
		root_files = { "tsconfig.json", "jsconfig.json", "package.json", ".git", ".jj" },
	},
	{
		lenguaje = "Tailwind CSS",
		id = "tailwindcss",
		enable = true,
		filetypes = { "html", "javascriptreact", "typescriptreact", "css" },
		root_files = { "tailwind.config.js", "tailwind.config.ts", "package.json", ".git", ".jj" },
	},
	{
		lenguaje = "Docker",
		id = "docker_language_server",
		enable = true,
		mason_name = "docker_language_server",
		filetypes = { "dockerfile" },
		root_files = { "Dockerfile", "docker-compose.yml", ".git", ".jj" },
	},
	{
		lenguaje = "JSON / JSONC",
		id = "jsonls",
		enable = true,
		mason_name = "json-lsp",
		filetypes = { "json", "jsonc" },
		root_files = { "package.json", "tsconfig.json", ".git", ".jj" },
	},
	{
		lenguaje = "YAML",
		id = "yamlls",
		enable = true,
		mason_name = "yaml-language-server",
		filetypes = { "yaml", "yaml.docker-compose", "yaml.gitlab" },
		root_files = { ".git", ".jj" },
	},
	{
		lenguaje = "SQL",
		id = "sqlls",
		enable = true,
		mason_name = "sql-language-server",
		filetypes = { "sql" },
		root_files = { ".git", ".jj", ".sqlconfig" },
	},
	{
		lenguaje = "Markdown",
		id = "marksman",
		enable = true,
		filetypes = { "markdown" },
		root_files = { ".git", ".jj", ".marksman.toml" },
	},
	{
		lenguaje = "Bash / Shell",
		id = "bashls",
		enable = true,
		mason_name = "bash-language-server",
		filetypes = { "sh", "bash" },
		root_files = { ".git", ".jj" },
	},
}
