#!/usr/bin/env sh


# bar settings
spacebar -m config position                    top
#spacebar -m config text_font                   "Menlo:Regular:12.0"
spacebar -m config text_font                   "MesloLGL Nerd Font"
spacebar -m config icon_font                   "Font Awesome 6 Free:Solid:12.0"

#spacebar -m config icon_font                   "feather:Regular:12.0"

# display settings
spacebar -m config display                     all
spacebar -m config display_separator           on
spacebar -m config display_separator_icon      ]

# components
spacebar -m config title                       on

spacebar -m config spaces                      on
spacebar -m config spaces_for_all_displays     on
#spacebar -m config space_icon                 0 1 2 3 4 5 6 7 8 9 
spacebar -m config space_icon_strip            0 1 2 3 4 5 6 7 8 9 
spacebar -m config space_icon_color            0xffffab91
spacebar -m config space_icon_color_secondary  0xff78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0

spacebar -m config clock                       on
spacebar -m config clock_format                "%R %d/%m/%y"
spacebar -m config clock_icon                  

spacebar -m config power                       on
spacebar -m config power_icon_strip            [] []
spacebar -m config dnd                         off 
spacebar -m config height                      42
spacebar -m config right_shell                 on
spacebar -m config right_shell_icon            " "
#spacebar -m config right_shell_command         "$HOME/Programs/bin/cmus-status &"

echo "spacebar configuration loaded.."

function icons --description "refresh status bar"
  while true
    $YABAI_SCRIPTS/toggle
    sleep 10
  end
end

icons
